[build]
  command = "hugo --gc"
  publish = "public"

[context.production.environment]
  HUGO_BASEURL = "https://cfpfinallive.netlify.app/"
  HUGO_VERSION = "0.111.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
